const accessoriesData = [
  {
    title: "black",
    image_url:
      "https://res.cloudinary.com/dv8h7yjv2/image/upload/v1738475228/public/Accessories-pics/m7gebv5igv5bnk0a8u0t.jpg",
    category: "Accessories",
    price: 104,
    available: 9,
  },
  {
    title: "connecting-rod",
    image_url:
      "https://res.cloudinary.com/dv8h7yjv2/image/upload/v1738475234/public/Accessories-pics/fxdi5ay6ppnjqho5dnnk.jpg",
    category: "Accessories",
    price: 57,
    available: 30,
  },
  {
    title: "crank",
    image_url:
      "https://res.cloudinary.com/dv8h7yjv2/image/upload/v1738475236/public/Accessories-pics/hqzccrcepafjp4xsik2e.jpg",
    category: "Accessories",
    price: 120,
    available: 8,
  },
  {
    title: "Diesel-filter",
    image_url:
      "https://res.cloudinary.com/dv8h7yjv2/image/upload/v1738475233/public/Accessories-pics/xrudpauxaky7oxjbisud.jpg",
    category: "Accessories",
    price: 119,
    available: 35,
  },
  {
    title: "Dynamo",
    image_url:
      "https://res.cloudinary.com/dv8h7yjv2/image/upload/v1738475236/public/Accessories-pics/zeye3wfosqii3ryimdcm.webp",
    category: "Accessories",
    price: 74,
    available: 26,
  },
  ,
  {
    title: "ECM-box",
    image: "/public/Accessories-pics/ECM-box.jpeg",
    category: "Accessories",
    price: 96,
    available: 25,
  },
  {
    title: "ECR-well",
    image: "/public/Accessories-pics/ECR-wall.jpeg",
    category: "Accessories",
    price: 34,
    available: 23,
  },
  {
    title: "engineoil-filter",
    image: "/public/Accessories-pics/engine-oil-filter.jpeg",
    category: "Accessories",
    price: 117,
    available: 16,
  },
  {
    title: "engine-pipes",
    image: "/public/Accessories-pics/engine-pipes.jpeg",
    category: "Accessories",
    price: 149,
    available: 18,
  },
  {
    title: "fan",
    image: "/public/Accessories-pics/fan.jpeg",
    category: "Accessories",
    price: 31,
    available: 29,
  },
  {
    title: "gearbox",
    image: "/public/Accessories-pics/gearbox.jpeg",
    category: "Accessories",
    price: 48,
    available: 32,
  },
  {
    title: "gear-rod",
    image: "/public/Accessories-pics/gear-rod.jpeg",
    category: "Accessories",
    price: 135,
    available: 39,
  },
  {
    title: "Head",
    image: "/public/Accessories-pics/Head.webp",
    category: "Accessories",
    price: 70,
    available: 8,
  },
  {
    title: "Injection-pump",
    image: "/public/Accessories-pics/injection-pump.png",
    category: "Accessories",
    price: 72,
    available: 35,
  },
  {
    title: "manifold",
    image: "/public/Accessories-pics/manifold.jpeg",
    category: "Accessories",
    price: 70,
    available: 21,
  },
  {
    title: "mount",
    image: "/public/Accessories-pics/mount.jpeg",
    category: "Accessories",
    price: 137,
    available: 25,
  },
  {
    title: "nozzle",
    image: "/public/Accessories-pics/nozzle.jpeg",
    category: "Accessories",
    price: 53,
    available: 25,
  },
  {
    title: "nozzle-pipes",
    image: "/public/Accessories-pics/nozzle-pipes.jpeg",
    category: "Accessories",
    price: 148,
    available: 31,
  },
  {
    title: "pulley",
    image: "/public/Accessories-pics/pulley.webp",
    category: "Accessories",
    price: 49,
    available: 28,
  },
  {
    title: "self-motor",
    image: "/public/Accessories-pics/self-motor.jpeg",
    category: "Accessories",
    price: 64,
    available: 29,
  },
  {
    title: "spingeret",
    image: "/public/Accessories-pics/spingerkit.jpeg",
    category: "Accessories",
    price: 125,
    available: 19,
  },
  {
    title: "sump",
    image: "/public/Accessories-pics/sump.jpeg",
    category: "Accessories",
    price: 87,
    available: 10,
  },
  {
    title: "turbo",
    image: "/public/Accessories-pics/turbo.jpeg",
    category: "Accessories",
    price: 92,
    available: 19,
  },
  {
    title: "walldoor",
    image: "/public/Accessories-pics/walldoor.jpeg",
    category: "Accessories",
    price: 47,
    available: 27,
  },
];

module.exports = { accessoriesData };
