const sampleEngines = [
  {
    title: "BS2",
    image: "/public/Engines-pics/AshokLeyland/BS2.jpeg",
    category: "Engine",
    EngineName: "Ashok Leyland",
    price: 100,
    available: 32,
    model: 2002,
    from: "Malibu, United States",
  },
  {
    title: "BS3",
    image: "/public/Engines-pics/AshokLeyland/BS3.jpeg",
    category: "Engine",
    EngineName: "Ashok Leyland",
    price: 50,
    available: 22,
    model: 2002,
    from: "Delhi",
  },
  {
    title: "BS4",
    image: "/public/Engines-pics/AshokLeyland/BS4.jpeg",
    category: "Engine",
    EngineName: "Ashok Leyland",
    price: 102,
    available: 49,
    model: 2007,
    from: "London, UK",
  },
  {
    title: "BS6",
    image: "/public/Engines-pics/AshokLeyland/BS6.webp",
    category: "Engine",
    EngineName: "Ashok Leyland",
    price: 100,
    available: 26,
    model: 2008,
    from: "Tokyo, Japan",
  },
  {
    title: "Bus",
    image: "/public/Engines-pics/AshokLeyland/Bus.webp",
    category: "Engine",
    EngineName: "Ashok Leyland",
    price: 97,
    available: 11,
    model: 2003,
    from: "London, UK",
  },
  {
    title: "Lorry",
    image: "/public/Engines-pics/AshokLeyland/Lorry.webp",
    category: "Engine",
    EngineName: "Ashok Leyland",
    price: 92,
    available: 43,
    model: 2009,
    from: "London, UK",
  },
  // Tata
  {
    title: "1512",
    image: "/public/Engines-pics/Tata/1512.jpeg",
    category: "Engine",
    EngineName: "TATA",
    price: 158,
    available: 47,
    model: 2016,
    from: "Malibu, United States",
  },
  {
    title: "1815",
    image: "/public/Engines-pics/Tata/1815.webp",
    category: "Engine",
    EngineName: "TATA",
    price: 132,
    available: 45,
    model: 2014,
    from: "Paris, France",
  },
  {
    title: "BS2",
    image: "/public/Engines-pics/Tata/BS2.jpeg",
    category: "Engine",
    EngineName: "TATA",
    price: 4,
    available: 190,
    model: 2003,
    from: "Rio",
  },
  {
    title: "BS3",
    image: "/public/Engines-pics/Tata/BS3.jpeg",
    category: "Engine",
    EngineName: "TATA",
    price: 74,
    available: 109,
    model: 2007,
    from: "America",
  },
  {
    title: "BS4",
    image: "/public/Engines-pics/Tata/BS4.jpeg",
    category: "Engine",
    EngineName: "TATA",
    price: 176,
    available: 29,
    model: 2005,
    from: "Tokyo",
  },
  {
    title: "BS5",
    image: "/public/Engines-pics/Tata/BS5.webp",
    category: "Engine",
    EngineName: "TATA",
    price: 174,
    available: 19,
    model: 2005,
    from: "Tokyo, Japan",
  },
  {
    title: "Cummins",
    image: "/public/Engines-pics/Tata/Cummins.webp",
    category: "Engine",
    EngineName: "TATA",
    price: 12,
    available: 145,
    model: 2021,
    from: "Paris, France",
  },
  {
    title: "Prima",
    image: "/public/Engines-pics/Tata/Prima.webp",
    category: "Engine",
    EngineName: "TATA",
    price: 156,
    available: 43,
    model: 2022,
    from: "London, UK",
  },
  {
    title: "Tipper",
    image: "/public/Engines-pics/Tata/Tipper.webp",
    category: "Engine",
    EngineName: "TATA",
    price: 100,
    available: 25,
    model: 2003,
    from: "Malibu, United States",
  },
  // Bharat Benz
  {
    title: "BS3",
    image: "/public/Engines-pics/BharatBenz/BS3.jpeg",
    category: "Engine",
    EngineName: "BHARAT BENZ",
    price: 47,
    available: 10,
    model: 2014,
    from: "Delhi, India",
  },
  {
    title: "BS4",
    image: "/public/Engines-pics/BharatBenz/BS4.jpeg",
    category: "Engine",
    EngineName: "BHARAT BENZ",
    price: 31,
    available: 19,
    model: 2003,
    from: "Delhi, India",
  },
  {
    title: "Tipper",
    image: "/public/Engines-pics/BharatBenz/Tipper.webp",
    category: "Engine",
    EngineName: "BHARAT BENZ",
    price: 47,
    available: 18,
    model: 2000,
    from: "Delhi, India",
  },
  {
    title: "Truck",
    image: "/public/Engines-pics/BharatBenz/Truck.webp",
    category: "Engine",
    EngineName: "BHARAT BENZ",
    price: 56,
    available: 42,
    model: 2005,
    from: "Malibu, United States",
  },
  // Eicher
  {
    title: "BS3",
    image: "/public/Engines-pics/Eicher/BS3.jpeg",
    category: "Engine",
    EngineName: "EICHER",
    price: 98,
    available: 16,
    model: 2002,
    from: "Delhi, India",
  },
  {
    title: "BS4",
    image: "/public/Engines-pics/Eicher/BS4.jpeg",
    category: "Engine",
    EngineName: "EICHER",
    price: 46,
    available: 24,
    model: 2004,
    from: "London, UK",
  },
  {
    title: "Eicher Pro",
    image: "/public/Engines-pics/Eicher/Eicherpro.webp",
    category: "Engine",
    EngineName: "EICHER",
    price: 141,
    available: 38,
    model: 2001,
    from: "Malibu, United States",
  },
];

module.exports = { sampleEngines };
